# Railway Deployment Configuration
# This tells Railway to use the backend directory

# Build settings
[build]
  builder = "NIXPACKS"
  
[build.env]
  NODE_VERSION = "22.12.0"

# Deploy settings
[deploy]
  startCommand = "cd backend && npm run start"
  healthcheckPath = "/_health"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
